# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='flightRefId',
            new_name='tripRefId',
        ),
    ]
