# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20191119_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('poiId', models.TextField()),
                ('cityCode', models.TextField()),
                ('cityName', models.TextField()),
                ('cityEName', models.TextField()),
                ('name', models.TextField()),
                ('countryName', models.TextField()),
                ('countryCode', models.TextField()),
                ('distance', models.IntegerField()),
                ('isDomestic', models.BooleanField(default=False)),
                ('isCanSelect', models.BooleanField(default=False)),
                ('airportCode', models.TextField()),
                ('provinceName', models.TextField()),
                ('provinceCode', models.TextField()),
                ('mapWord', models.TextField()),
                ('dataType', models.IntegerField()),
                ('airportShortName', models.TextField()),
                ('virtualRegionCode', models.TextField()),
                ('timeZone', models.IntegerField()),
                ('poiParentId', models.IntegerField()),
            ],
            options={
                'db_table': 'POIInfo',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='flight',
            name='aPortCode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dPortCode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='luggageDirectDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='luggageDirectStatus',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='luggageDirectTitle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cityStopList',
            field=models.TextField(null=True),
        ),
    ]
