# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20191119_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='alliance',
            field=models.TextField(null=True),
        ),
    ]
