# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20191119_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airlineRefId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='craftRefId',
            field=models.IntegerField(null=True),
        ),
    ]
