# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20191119_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='subid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
