# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20191120_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='subid',
            new_name='tripSubId',
        ),
    ]
