# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20191120_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='scheduleSubId',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
