# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_trip_schedulesubid'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bizId',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
