# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_schedule_bizid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrivalDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='currency',
            field=models.TextField(default='USD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='durationMin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='isLowestPrice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='isShortestDrt',
            field=models.BooleanField(default=False),
        ),
    ]
