# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20191120_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='mainClass',
            field=models.TextField(default='Economy'),
            preserve_default=False,
        ),
    ]
