# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_price_mainclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='version',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='version',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='version',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='version',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
