# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20191121_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departureCityCode', models.TextField()),
                ('arrivalCityCode', models.TextField()),
                ('scheduleDate', models.DateField()),
                ('respData', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('version', models.TextField()),
            ],
            options={
                'db_table': 'response',
            },
        ),
    ]
